---
#**EXTRACTION METHOD**
---

# Install necessary dependencies

In [1]:
import nltk
import numpy as np
import pandas as pd
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Get Text Document

We use the description of a very popular role-playing game (RPG) Skyrim from
Bethesda Softworks for summarization. 

In [2]:
DOCUMENT = """
The Elder Scrolls V: Skyrim is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.

It is the fifth main installment in The Elder Scrolls series, following The Elder Scrolls IV: Oblivion.
"""

In [3]:
import re
DOCUMENT = re.sub(r'\n|\r', ' ', DOCUMENT) #Combining all the paragraphs
DOCUMENT = re.sub(r' +', ' ', DOCUMENT)
DOCUMENT = DOCUMENT.strip()

In [4]:
print(DOCUMENT)

The Elder Scrolls V: Skyrim is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks. It is the fifth main installment in The Elder Scrolls series, following The Elder Scrolls IV: Oblivion.


Sentences Collection

In [5]:
sentences = nltk.sent_tokenize(DOCUMENT)
print(sentences)
print("No. of sentences:",len(sentences))

['The Elder Scrolls V: Skyrim is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', 'It is the fifth main installment in The Elder Scrolls series, following The Elder Scrolls IV: Oblivion.']
No. of sentences: 2


# Basic Text pre-processing

In [6]:
stop_words = nltk.corpus.stopwords.words('english')

def normalize_document(doc):
    # lower case and remove special characters\whitespaces
    doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    # tokenize document
    tokens = nltk.word_tokenize(doc)
    # filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc

normalize_corpus = np.vectorize(normalize_document) #Function Def Vectorize
norm_sentences = normalize_corpus(sentences)
norm_sentences[:3]

array(['elder scrolls v skyrim action roleplaying video game developed bethesda game studios published bethesda softworks',
       'fifth main installment elder scrolls series following elder scrolls iv oblivion'],
      dtype='<U113')

# *I - UNIGRAM*

In [7]:
# Creation of Unigarms
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(ngram_range =(1, 1))
X1 = vectorizer.fit_transform(norm_sentences)
unigrams = (vectorizer.get_feature_names())
print(unigrams)
print(len(unigrams))

['action', 'bethesda', 'developed', 'elder', 'fifth', 'following', 'game', 'installment', 'iv', 'main', 'oblivion', 'published', 'roleplaying', 'scrolls', 'series', 'skyrim', 'softworks', 'studios', 'video']
19


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


##TF

In [8]:
print("Norm Sentences:", norm_sentences)
print("Len of Norm Sentences:", len(norm_sentences))

Norm Sentences: ['elder scrolls v skyrim action roleplaying video game developed bethesda game studios published bethesda softworks'
 'fifth main installment elder scrolls series following elder scrolls iv oblivion']
Len of Norm Sentences: 2


In [9]:
def computeTF(doc):
  valTF = []
  for each in doc:
    wordDict = dict.fromkeys(unigrams, 0)
    sentence = each.split(" ")

    for word in sentence:
      if len(word) == 1:
        sentence.remove(word)

    for word in sentence:
      wordDict[word]+=1

    res = []
    for i in wordDict:
      comp = float(wordDict[i] / len(each))
      res.append(round(comp, 4))
    
    valTF.append(res)
  return(valTF)
    
TF = computeTF(norm_sentences)

In [10]:
TF = np.array(TF)
TF = TF.T
type(TF)

numpy.ndarray

In [11]:
df = pd.DataFrame(TF, index=unigrams)
df.sort_index(ascending=True).head(10)

0       1
action       0.0088  0.0000
bethesda     0.0177  0.0000
developed    0.0088  0.0000
elder        0.0088  0.0253
fifth        0.0000  0.0127
following    0.0000  0.0127
game         0.0177  0.0000
installment  0.0000  0.0127
iv           0.0000  0.0127
main         0.0000  0.0127

##DF (Document Frequency/Term Presence)

In [12]:
DF = vectorizer.fit_transform(norm_sentences)
DF = DF.toarray()
DF = DF.T
DF

array([[1, 0],
       [2, 0],
       [1, 0],
       [1, 2],
       [0, 1],
       [0, 1],
       [2, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 2],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

In [13]:
df = pd.DataFrame(DF, index=unigrams)
df

0  1
action       1  0
bethesda     2  0
developed    1  0
elder        1  2
fifth        0  1
following    0  1
game         2  0
installment  0  1
iv           0  1
main         0  1
oblivion     0  1
published    1  0
roleplaying  1  0
scrolls      1  2
series       0  1
skyrim       1  0
softworks    1  0
studios      1  0
video        1  0

##TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(min_df=0., max_df=1., use_idf=True)
dt_matrix = tv.fit_transform(norm_sentences)
dt_matrix = dt_matrix.toarray() 

In [15]:
td_matrix = dt_matrix.T #Transpose Matrix
td_matrix
print(td_matrix.shape)

(19, 2)


In [16]:
pd.DataFrame(np.round(td_matrix, 2), index=unigrams)

0     1
action       0.24  0.00
bethesda     0.48  0.00
developed    0.24  0.00
elder        0.17  0.43
fifth        0.00  0.30
following    0.00  0.30
game         0.48  0.00
installment  0.00  0.30
iv           0.00  0.30
main         0.00  0.30
oblivion     0.00  0.30
published    0.24  0.00
roleplaying  0.24  0.00
scrolls      0.17  0.43
series       0.00  0.30
skyrim       0.24  0.00
softworks    0.24  0.00
studios      0.24  0.00
video        0.24  0.00

# *II - BIGRAM* 

In [18]:
# Forming Bigrams
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(ngram_range = (2,2))
X1 = vectorizer.fit_transform(norm_sentences) 
bigrams = (vectorizer.get_feature_names())
print("\n\nFeatures : \n", bigrams)
print("\n\nX1 : \n", X1.toarray())



Features : 
 ['action roleplaying', 'bethesda game', 'bethesda softworks', 'developed bethesda', 'elder scrolls', 'fifth main', 'following elder', 'game developed', 'game studios', 'installment elder', 'iv oblivion', 'main installment', 'published bethesda', 'roleplaying video', 'scrolls iv', 'scrolls series', 'scrolls skyrim', 'series following', 'skyrim action', 'studios published', 'video game']


X1 : 
 [[1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 1 0 1 1 1]
 [0 0 0 0 2 1 1 0 0 1 1 1 0 0 1 1 0 1 0 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


## TF

In [19]:
print("Norm Sentences:", norm_sentences)
print("Len of Norm Sentences:", len(norm_sentences))

Norm Sentences: ['elder scrolls v skyrim action roleplaying video game developed bethesda game studios published bethesda softworks'
 'fifth main installment elder scrolls series following elder scrolls iv oblivion']
Len of Norm Sentences: 2


In [22]:
wordDict = dict.fromkeys(bigrams, 0)
wordDict

{'action roleplaying': 0,
 'bethesda game': 0,
 'bethesda softworks': 0,
 'developed bethesda': 0,
 'elder scrolls': 0,
 'fifth main': 0,
 'following elder': 0,
 'game developed': 0,
 'game studios': 0,
 'installment elder': 0,
 'iv oblivion': 0,
 'main installment': 0,
 'published bethesda': 0,
 'roleplaying video': 0,
 'scrolls iv': 0,
 'scrolls series': 0,
 'scrolls skyrim': 0,
 'series following': 0,
 'skyrim action': 0,
 'studios published': 0,
 'video game': 0}

In [ ]:
def TF_ngram(n, doc):
  for each in 

In [20]:
def computeTF(doc):
  valTF = []
  for each in doc:
    wordDict = dict.fromkeys(bigrams, 0)
    sentence = each.split(" ")

    for word in sentence:
      if len(word) == 1:
        sentence.remove(word)

    for word in sentence:
      wordDict[word]+=1

    res = []
    for i in wordDict:
      comp = float(wordDict[i] / len(each))
      res.append(round(comp, 4))
    
    valTF.append(res)
  return(valTF)
    
TF = computeTF(norm_sentences)

KeyError: ignored

## TF-IDF

In [23]:
# Applying TFIDF
vectorizer = TfidfVectorizer(ngram_range = (2, 2))
X2 = vectorizer.fit_transform(norm_sentences)
scores = (X2.toarray())
print("\n\nScores : \n", scores)



Scores : 
 [[0.2827721  0.2827721  0.2827721  0.2827721  0.20119468 0.
  0.         0.2827721  0.2827721  0.         0.         0.
  0.2827721  0.2827721  0.         0.         0.2827721  0.
  0.2827721  0.2827721  0.2827721 ]
 [0.         0.         0.         0.         0.44943642 0.3158336
  0.3158336  0.         0.         0.3158336  0.3158336  0.3158336
  0.         0.         0.3158336  0.3158336  0.         0.3158336
  0.         0.         0.        ]]
